# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version

<module 'numpy.version' from 'C:\\Users\\galic156685\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
a=np.random.random((2,3,5))

In [ ]:
# Method 2


In [ ]:
# Method 3

#### 4. Print *a*.


In [6]:
# your code here
a

array([[[0.05807341, 0.20689015, 0.95149938, 0.68553829, 0.44114373],
        [0.19795916, 0.44357956, 0.45333742, 0.77945769, 0.93984977],
        [0.60371718, 0.10655119, 0.34870845, 0.35804838, 0.97592427]],

       [[0.26635564, 0.0194567 , 0.0861243 , 0.7713254 , 0.5476268 ],
        [0.45661741, 0.35764504, 0.11338135, 0.52233549, 0.17670936],
        [0.34324579, 0.06489675, 0.18267601, 0.68673435, 0.25032869]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [58]:
# your code here
b=np.full((5,2,3), 1)

#### 6. Print *b*.


In [59]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [17]:
# your code here
print(a.shape, b.shape)

(2, 3, 5) (5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [ ]:
# your answer here
#we can't add a and b because they don'y have the same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [36]:
# your code here
c=np.transpose(b, (1, 2, 0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [39]:
# your code/answer here
d=np.add(a,c)

[[[1.05807341 1.20689015 1.95149938 1.68553829 1.44114373]
  [1.19795916 1.44357956 1.45333742 1.77945769 1.93984977]
  [1.60371718 1.10655119 1.34870845 1.35804838 1.97592427]]

 [[1.26635564 1.0194567  1.0861243  1.7713254  1.5476268 ]
  [1.45661741 1.35764504 1.11338135 1.52233549 1.17670936]
  [1.34324579 1.06489675 1.18267601 1.68673435 1.25032869]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [41]:
# your code/answer here
print(a)
print("next")
print(d)
#d is the sum of the elements of a and b 

[[[0.05807341 0.20689015 0.95149938 0.68553829 0.44114373]
  [0.19795916 0.44357956 0.45333742 0.77945769 0.93984977]
  [0.60371718 0.10655119 0.34870845 0.35804838 0.97592427]]

 [[0.26635564 0.0194567  0.0861243  0.7713254  0.5476268 ]
  [0.45661741 0.35764504 0.11338135 0.52233549 0.17670936]
  [0.34324579 0.06489675 0.18267601 0.68673435 0.25032869]]]
next
[[[1.05807341 1.20689015 1.95149938 1.68553829 1.44114373]
  [1.19795916 1.44357956 1.45333742 1.77945769 1.93984977]
  [1.60371718 1.10655119 1.34870845 1.35804838 1.97592427]]

 [[1.26635564 1.0194567  1.0861243  1.7713254  1.5476268 ]
  [1.45661741 1.35764504 1.11338135 1.52233549 1.17670936]
  [1.34324579 1.06489675 1.18267601 1.68673435 1.25032869]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [45]:
# your code here
e=a*c
print(e)

[[[0.05807341 0.20689015 0.95149938 0.68553829 0.44114373]
  [0.19795916 0.44357956 0.45333742 0.77945769 0.93984977]
  [0.60371718 0.10655119 0.34870845 0.35804838 0.97592427]]

 [[0.26635564 0.0194567  0.0861243  0.7713254  0.5476268 ]
  [0.45661741 0.35764504 0.11338135 0.52233549 0.17670936]
  [0.34324579 0.06489675 0.18267601 0.68673435 0.25032869]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
# e is egal to a because each elements of c are 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [48]:
# your code here
d_mean=np.mean(d)
d_max=np.max(d)
d_min=np.min(d)
print(d_max, d_min, d_mean)

1.9759242671115813 1.0194567000109436 1.4131912366860306


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [67]:
# your code here
f=np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [77]:
# your code here
f[d==d_max]=100
f[d<d_max]=75
f[d==d_mean]=50
f[d<d_mean]=25
f[d==d_min]=0
np.array(list(map(lambda x: 100 if x==d_max else 75 if x<d_max else 50 if x==d_mean else 25 if x<d_mean else 0 if x==d_min,d.ravel))).reshape(2,3,5)

f [[[ 25.  25.  75.  75.  75.]
  [ 25.  75.  75.  75.  75.]
  [ 75.  25.  25.  25. 100.]]

 [[ 25.   0.  25.  75.  75.]
  [ 75.  25.  25.  75.  25.]
  [ 25.  25.  25.  75.  25.]]] d [[[1.05807341 1.20689015 1.95149938 1.68553829 1.44114373]
  [1.19795916 1.44357956 1.45333742 1.77945769 1.93984977]
  [1.60371718 1.10655119 1.34870845 1.35804838 1.97592427]]

 [[1.26635564 1.0194567  1.0861243  1.7713254  1.5476268 ]
  [1.45661741 1.35764504 1.11338135 1.52233549 1.17670936]
  [1.34324579 1.06489675 1.18267601 1.68673435 1.25032869]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [78]:
# your code here
print("f",f)
print("d",d)

f [[[ 25.  25.  75.  75.  75.]
  [ 25.  75.  75.  75.  75.]
  [ 75.  25.  25.  25. 100.]]

 [[ 25.   0.  25.  75.  75.]
  [ 75.  25.  25.  75.  25.]
  [ 25.  25.  25.  75.  25.]]]
d [[[1.05807341 1.20689015 1.95149938 1.68553829 1.44114373]
  [1.19795916 1.44357956 1.45333742 1.77945769 1.93984977]
  [1.60371718 1.10655119 1.34870845 1.35804838 1.97592427]]

 [[1.26635564 1.0194567  1.0861243  1.7713254  1.5476268 ]
  [1.45661741 1.35764504 1.11338135 1.52233549 1.17670936]
  [1.34324579 1.06489675 1.18267601 1.68673435 1.25032869]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [82]:
# your code here
f=f.astype(object)
f[f==100]='E'
f[f==75]='D'
f[f==50]='C'
f[f==25]='B'
f[f==0]='A'

In [83]:
f

array([[['B', 'B', 'D', 'D', 'D'],
        ['B', 'D', 'D', 'D', 'D'],
        ['D', 'B', 'B', 'B', 'E']],

       [['B', 'A', 'B', 'D', 'D'],
        ['D', 'B', 'B', 'D', 'B'],
        ['B', 'B', 'B', 'D', 'B']]], dtype=object)

In [85]:
g[[f==100]='E',f[f==75]='D',f[f==50]='C',f[f==25]='B',f[f==0]='A']

SyntaxError: invalid syntax (<ipython-input-85-29956cb9a842>, line 1)